name: expense_tracker
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^5.0.0
  responsive_framework: ^1.4.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


  fonts:
    - family: Poppins
      fonts:
        # - asset: fonts/Poppins-Regular.ttf
        # - asset: fonts/Poppins-Bold.ttf